### DISCUSSION TITLE
Oqtane with Docker

### DISCUSSION THREAD

**Discussion by Sharafudeen** [oqtane/oqtane.framework#2091] [General]
Any plans for Docker container feature added in Oqtane?

I've read an article, if we can develop dotnet core application with Docker then "dotnet core dependencies / prerequisites is not required?"

Thanks & Regards!

**Comment by Sharafudeen** [comment]
@sbwalker any updates on this?

**Reply by sbwalker** [reply]
I am not sure what you are asking but if you want to run Oqtane on Docker please go ahead. If you run into any difficulties please share your findings so that others could benefit from the knowledge.

**Reply by Sharafudeen** [reply]
Actually I don't know how to setup & publish Oqtane with Docker container. Is there any special setups required for Docker in Oqtane?

**Comment by Behnam-Emamian** [comment]
I have started running Oqtane on Docker. The biggest challenge is that Oqtane manipulates files frequently. However, since the Docker image is immutable, we need to find a way to change Oqtane’s behavior without changing the files.

**Reply by sbwalker** [reply]
@Behnam-Emamian by "manipulation of files" you are referring to core functionality such as the install wizard, the ability to install modules and themes, auto upgrade of the framework, etc... It would be very difficult to find alternatives for this functionality. One possible option is to just document that if you choose to run on a constrained environment like Docker the framework will be "crippled" in certain ways.

**Reply by Behnam-Emamian** [reply]
you are right, docker image is like a snapshot of the environment and we cannot make any changes and because of that we can have several instances.

My solution is publishing the framework and all modules together and build an image from that.

**Reply by timdinh** [reply]
docker image is immutable but the running container is not. you can map a directory inside a container to a directory on the host.

I'm trying to build a docker image from `Oqtane.Framework.4.0.1.Install.zip`. This is my `Dockerfile` content

```
FROM mcr.microsoft.com/dotnet/aspnet:7.0 
ENV TZ=Australia/Sydney \
    ASPNETCORE_URLS=http://+:80
EXPOSE 80/tcp
WORKDIR /app
COPY ["Oqtane.Framework.4.0.1.Install/", "."]
ENTRYPOINT ["dotnet", "Oqtane.Server.dll"]
```

and below is the content of my docker-compose.yml file
```
version: '3.8'

services:
  oqtane:
    build: 
      context: .
      dockerfile: Dockerfile
      tags: ["latest","4.0.1"]
    ports:
      - "8088:80"
    depends_on:
      - db-service
    environment:
      - "ASPNETCORE_URLS=http://+:80"
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "ConnectionStrings__DefaultConnection=Server=db-service;Port=5432;Database=oqtane;User Id=postgres;Password=dev123;"
    networks:
      - octane-net
    volumes:
      - ./data:/app/Data
      - ./content:/app/Content
    mem_limit: 1g

  db-service:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=oqtane
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    networks:
      - octane-net
    mem_limit: 1g

volumes:
  oqtane_db:
  oqtane_fs:

networks:
  octane-net:
```


Unfortunately, i run into an error message when starting the container and navigate to the page, the error is
```
[2023-07-23 17:28:42+00:00] [Error] An exception was thrown while deserializing the token.    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

I guess it has something to do with `Antiforgery` due to the app running inside a docker container.

I'm trying to find a solution now but if anyone has any ideas i would appreciate the help

**Reply by yem583** [reply]
I don't think that has anything to do with Oqtane, that is straight up Asp.net, if you want to run Asp.net in a container, you need to configure DataProtection to a volume that persists beyond the container's lifetime, such as a shared volume or a host-mounted volume (also external providers would work as well (redis/blob storage, etc))

Based on your dockercompose above (thank you btw - it was my starting point for this), you could add something like this. 

            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(@"/app/Data/keys"))
                .SetApplicationName("Oqtane");

This is working for me after adding this to startup in Oqtane Server project.  What's not clear to me is what the proper pattern is in Oqtane to doing something like this.  I don't intend to change any of the Oqtane source code to ensure smooth updates, so this is likely a temporary fix.  

Hope that helps.


related MS Docs
https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-8.0#persisting-keys-when-hosting-in-a-docker-container

**Reply by sbwalker** [reply]
@yem583 additional services can be registered in Oqtane by implementing the IServerStartup class:

```
    public class ServerStartup : IServerStartup
    {
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            // not implemented
        }

        public void ConfigureMvc(IMvcBuilder mvcBuilder)
        {
            // not implemented
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(@"/app/Data/keys"))
                .SetApplicationName("Oqtane");        }
    }
```

Basically, scaffold a new module (ie. login as host, navigate to /admin/modules, select Create Module) and include the logic in the Startup/ServerStartup.cs file in the Server project - and build it. At runtime, Oqtane will load the assembly and automatically register the service as part of startup.

**Reply by yem583** [reply]
fantastic, thanks for the reply @sbwalker

**Reply by yem583** [reply]
in case anyone else is wanting to do something like this.  I was able to get Oqtane running in Azure Container Apps.  The only other challenge I ran into, is I initially had different ports for my host and my container, this caused in issue with the local api (see PrivateApi Attribute), the HttpClient used for those internal api calls, will default to the host url, but that won't work.  I made both the host and container ports the same and bingo, it worked.  This isn't a final solution for my project as I need this container app to be consistent with all the others in our environment, but for now (POC), this will work fine.  Now onto the fun stuff.
![image](https://github.com/user-attachments/assets/77d0de36-ea9c-4cf5-894f-6686d2b89f4d)

**Reply by sbwalker** [reply]
@yem583 I would love to hear more about your Azure Container App configuration for Oqtane

**Reply by mdmontesinos** [reply]
@yem583 I'd also love to hear about it!! Making Oqtane installable in an Azure Container App is really nice when talking in terms of scalability and reliability.

**Reply by jkeeley2073** [reply]
@mdmontesinos @sbwalker - For local development I'm running docker compose.
```yaml
services:
   oqtane.server:
    build: 
      context: .
      dockerfile: Oqtane.Server/Dockerfile
      tags: ["latest","5.2.3"]
    ports:
      - "8080:8080"
    depends_on:
      - sqldata
    environment:
      - "ASPNETCORE_URLS=http://+:8080"
      - "ASPNETCORE_HTTP_PORTS=8080"
      - "ASPNETCORE_ENVIRONMENT=Development"
    networks:
      - octane-net
    volumes:
      - ./data:/app/Data
      - ./content:/app/Content
    mem_limit: 1g

   sqldata:
     image: mcr.microsoft.com/mssql/server:2022-latest 
     environment:
       - "SA_PASSWORD=**********"
       - "ACCEPT_EULA=Y"
     networks:
       - octane-net
     volumes:
       - oqtane_db:/var/opt/mssql
     ports:
       - "1533:1433"
volumes:
  oqtane_db:
  oqtane_fs:

networks:
  octane-net:
```

And my dockerfile
```
# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_HTTP_PORTS=8080
ENV ASPNETCORE_ENVIRONMENT=Production

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Oqtane.Server/Oqtane.Server.csproj", "Oqtane.Server/"]
COPY ["Oqtane.Client/Oqtane.Client.csproj", "Oqtane.Client/"]
COPY ["Oqtane.Shared/Oqtane.Shared.csproj", "Oqtane.Shared/"]
COPY ["Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj", "Oqtane.Database.MySQL/"]
COPY ["Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj", "Oqtane.Database.PostgreSQL/"]
COPY ["Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj", "Oqtane.Database.SqlServer/"]
COPY ["Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj", "Oqtane.Database.Sqlite/"]

RUN dotnet restore "Oqtane.Server/Oqtane.Server.csproj"
RUN dotnet restore "Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj"

COPY . .

WORKDIR "/src/Oqtane.Database.MySQL"
RUN dotnet build "Oqtane.Database.MySQL.csproj" -c $BUILD_CONFIGURATION -o /app/build

WORKDIR "/src/Oqtane.Database.PostgreSQL"
RUN dotnet build "Oqtane.Database.PostgreSQL.csproj" -c $BUILD_CONFIGURATION -o /app/build

WORKDIR "/src/Oqtane.Database.SqlServer"
RUN dotnet build "Oqtane.Database.SqlServer.csproj" -c $BUILD_CONFIGURATION -o /app/build

WORKDIR "/src/Oqtane.Database.Sqlite"
RUN dotnet build "Oqtane.Database.Sqlite.csproj" -c $BUILD_CONFIGURATION -o /app/build

WORKDIR "/src/Oqtane.Server"
#RUN dotnet build "Oqtane.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Oqtane.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY Oqtane.Server/appsettings.json . 
ENTRYPOINT ["dotnet", "Oqtane.Server.dll"]
```

In my devops pipeline, I'm publishing the container image to azure container registry and using Azure CLI azure container app update to deploy to container app.  I'm also using Azure File Share in Azure ContainerApps to mount a shared drive to support shared persistent storage.

![image](https://github.com/user-attachments/assets/287de806-e10d-44de-a4dc-d0d4deece690)
![image](https://github.com/user-attachments/assets/c331de51-4293-49d2-aee7-fc381b203bdc)

Couple of other notes: Ran into issues trying to use Azure Sql (issues with permissions to Master DB), so currently I'm running SQL Server in a container app.  That won't be supported in our production environment so I still need to solve that (several possible options).  I'd also like to replace docker-compose with Aspire. I have not yet started to build any modules yet. 

I'm happy to provide additional details, or try and answer any other questions if you guys have any.  Also appreciate any suggestions or insights.

![image](https://github.com/user-attachments/assets/6d0cb47b-4b61-439c-9b7c-2c80177b8579)
