### DISCUSSION TITLE
Getting Started With Oqtane and Docker

### DISCUSSION THREAD

**Discussion by mikecasas** [oqtane/oqtane.framework#692] [General]
There are two Oqtane images on Dockerhub, one is the web application and the other is the SQL Server database.

Prerequisites - assumes you have a docker environment installed. (I am using Docker Desktop on Windows)
1. Copy the ```docker-compose.yaml``` file to your machine (File is at the bottom or the gist located at https://gist.github.com/mikecasas/6937bccf48097fe37261fc81323acea0). 

2. From a command line, navigate to the folder where you saved the ```docker-compose.yaml``` file.
3. Run the command ```docker-compose up```. It will take a while for the images to download. 
4. Once the containers are running, navigate in your browser to ```http://localhost:6001```. You should see the Oqtane Installation page.
5. From the command line, run ```docker ps``` to see the running containers. Get the container id of the SQL Server container.
6. Once you have the container id, from the command line, run docker ```inspect``` to get the IP address of the SQL container. 
```
       docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container-id-goes-here
```

![powersehll-commands](https://user-images.githubusercontent.com/11261164/90581852-452cd280-e19a-11ea-9f05-92b6a9050612.PNG)

7. Enter the IP address of the SQL container followed by ",1433" for the port. Below is a screen shot. 
 * The SQL password is ```Password1``` 

![oqtane-db-settings](https://user-images.githubusercontent.com/11261164/90581982-9ccb3e00-e19a-11ea-97ea-e704af488e6e.PNG)

8. Click ```Install Now```

## docker-compose.yaml
```
version: "3.4"
services:
 app-oqtane:
  container_name: oqtane-app
  image: mkcsas/oqtane-app:v1
  ports:
  - "6001:6001"
 db:
  container_name: oqtane-sql
  image: mkcsas/oqtane-sql-base:v1.0.1
  ports: 
  - "1433:1433"
```
