### ISSUE TITLE
[BUG] Install with PostgreSQL in Docker error: Object reference not set to an instance of an object at RewriteName(String name)

### ISSUE THREAD

**Issue by pollux** [oqtane/oqtane.framework#4770]
### Oqtane Info

Version - 5.2.4
Render Mode - Static 
Interactivity - Server
Database - PostgreSQL

### Environment Info

- Docker: `27.2.0, build 3ab4256`
- Docker compose: `v2.29.2-desktop.2`
- Docker Desktop: `4.34.2 (167172)`
- Host: Windows 11 Home

### Describe the bug

When installing Oqtane with a PostgreSQL database the installer runs into an error.
When doing the same with a Microsoft SQL Server it works.

**Error**:
![image](https://github.com/user-attachments/assets/dc6dedfb-f3c1-44ae-8dd4-27f36f920b1e)

### Expected Behavior

The Installer not running into an error.

### Steps To Reproduce

1. Spin up an instance through the provided Compose file (the Dockerfile will be built automatically)
2. Connect to Oqtane via Web Browser, e.g. http://localhost
3. Fill out the install form
5. Click "Install"

### Anything else?

**Dockerfile**
```Dockerfile
# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_HTTP_PORTS=80
ENV ASPNETCORE_ENVIRONMENT=Production

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Oqtane.Server/Oqtane.Server.csproj", "Oqtane.Server/"]
COPY ["Oqtane.Client/Oqtane.Client.csproj", "Oqtane.Client/"]
COPY ["Oqtane.Shared/Oqtane.Shared.csproj", "Oqtane.Shared/"]
COPY ["Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj", "Oqtane.Database.MySQL/"]
COPY ["Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj", "Oqtane.Database.PostgreSQL/"]
COPY ["Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj", "Oqtane.Database.SqlServer/"]
COPY ["Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj", "Oqtane.Database.Sqlite/"]

RUN dotnet restore "Oqtane.Server/Oqtane.Server.csproj"
RUN dotnet restore "Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj"
RUN dotnet restore "Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj"

COPY . .

RUN dotnet build "Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj" -c $BUILD_CONFIGURATION -o /app/build/

RUN dotnet build "Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj" -c $BUILD_CONFIGURATION -o /app/build/

RUN dotnet build "Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj" -c $BUILD_CONFIGURATION -o /app/build/

RUN dotnet build "Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj" -c $BUILD_CONFIGURATION -o /app/build/

WORKDIR "/src/Oqtane.Server"
#RUN dotnet build "Oqtane.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Oqtane.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY Oqtane.Server/appsettings.json . 
ENTRYPOINT ["dotnet", "Oqtane.Server.dll"]
```

**Docker Compose - Microsoft SQL Server**
```yml
name: oqtane

services:
    oqtane.server:
        container_name: oqtane-dev
        restart: unless-stopped
        build: 
          context: .
          dockerfile: Dockerfile
          tags: ["latest","5.2.4"]
        ports:
            - "80:80"
        depends_on:
            - sqldata
        environment:
            - "ASPNETCORE_URLS=http://+:80"
            - "ASPNETCORE_HTTP_PORTS=80"
            - "ASPNETCORE_ENVIRONMENT=Development"
        networks:
            - octane-net
        volumes:
            - "C:/OqtaneVolumes/appsettings.json:/app/appsettings.json:rw"
            - "C:/OqtaneVolumes/Data:/app/Data:rw"
            - "C:/OqtaneVolumes/Content:/app/Content:rw"
            - "C:/OqtaneVolumes/Packages:/app/Packages:rw"
        mem_limit: 1g

    sqldata:
        image: mcr.microsoft.com/mssql/server:2022-latest 
        environment:
            - "SA_PASSWORD=SecureDB2024-"
            - "ACCEPT_EULA=Y"
        networks:
            - octane-net
        volumes:
            - oqtane_db:/var/opt/mssql
        ports:
        - "1533:1433"
volumes:
    oqtane_db:
    oqtane_fs:

networks:
    octane-net:
```

**Docker Compose - PostgreSQL**
```yml
name: oqtane

services:
    oqtane.server:
        container_name: oqtane-dev
        restart: unless-stopped
        build: 
          context: .
          dockerfile: Dockerfile
          tags: ["latest","5.2.4"]
        ports:
            - "80:80"
        depends_on:
            - postgresql-data
        environment:
            - "ASPNETCORE_URLS=http://+:80"
            - "ASPNETCORE_HTTP_PORTS=80"
            - "ASPNETCORE_ENVIRONMENT=Development"
        networks:
            - octane-net
        volumes:
            - "C:/OqtaneVolumes/appsettings.json:/app/appsettings.json:rw"
            - "C:/OqtaneVolumes/Data:/app/Data:rw"
            - "C:/OqtaneVolumes/Content:/app/Content:rw"
            - "C:/OqtaneVolumes/Packages:/app/Packages:rw"
        mem_limit: 1g

    postgresql-data:
        restart: unless-stopped
        image: postgres:13
        container_name: oqtane-database
        environment:
            - "POSTGRES_PASSWORD=postgres"
            - "POSTGRES_USER=postgres"
            - "PGDATA=/var/lib/postgresql/data"
        networks:
            - octane-net
        volumes:
            - "C:/OqtaneVolumes/postgresdata:/var/lib/postgresql/data:rw"
        ports:
            - "5432:5432"
volumes:
    oqtane_db:
    oqtane_fs:

networks:
    octane-net:
```
